name: Node.js Docs CI
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Build docs
      run: npm run docs
    - name: Ensure there are no changes in docs
      run: git diff --exit-code docs/
