name: Node.js Unit CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        node-version: [16]
        dapr-version: [1.6.3, 1.7.4, 1.8.1]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dapr
        uses: dapr/setup-dapr@v1
        with:
          version: '1.8.0'
      - name: Install Docker for macOS
        uses: docker-practice/actions-setup-docker@master
        if: ${{ matrix.platform == 'macos-latest' }}
      - name: Initialize Dapr
        run: dapr init -s --runtime-version ${{ matrix.dapr-version }}
      - name: Install dependencies
        run: npm install
      - name: Build TypeScript project
        run: npm run build --if-present
      - name: Test
        run: npm test
